name: Build and Test
on: [push, pull_request]
jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dio
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}
      - name: phpize
        run: phpize
      - name: configure
        run: ./configure --enable-dio
      - name: make
        run: make
      - name: test
        run: make test TESTS="tests --show-diff"
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        version: ['8.3']
        arch: [x64]
        ts: [ts]
    runs-on: windows-latest
    steps:
      - name: Checkout dio
        uses: actions/checkout@v4
      - name: Extract Version
        shell: powershell
        run: |
          chcp 65001
          $r = Select-String -Path src/php_dio.h -Pattern 'PHP_DIO_VERSION\s+"(.*)"'
          $s = $r.Matches[0].Groups[1]
          echo "$s"
          $extension_version = 'EXTENSION_VERSION=' + $s
          echo $extension_version >> $env:GITHUB_ENV
      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          extension-ref: ${{env.EXTENSION_VERSION}}
          php-version: ${{matrix.version}}
          ts: ${{matrix.ts}}
          arch: ${{matrix.arch}}
          args: --enable-dio
          run-tests: false
      - name: test
        run: nmake test TESTS="tests --show-diff"
      - name: Upload artifact to the release
        uses: php/php-windows-builder/release@v1
        with:
          release: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
